# Generated by Django 5.1.5 on 2025-02-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='direction',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
