# Generated by Django 5.1.5 on 2025-02-01 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_alter_userdata_direction_alter_userdata_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='material_file_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='direction',
            field=models.CharField(max_length=255),
        ),
    ]
